logging:
  level:
    root: info
    # Maze
    tech.maze: info
    # database
    org.hibernate.SQL: warn
    com.zaxxer.hikari.HikariConfig: warn
    com.zaxxer.hikari: warn

spring:
  main:
    banner-mode: 'off'
  datasource:
    enabled: true
    default:
      configuration:
        maximum-pool-size: 2
        minimum-idle: 2 # INFO: minimum number of idle connections maintained by HikariCP in a connection pool
        max-lifetime: 1800000 # INFO: maximum lifetime in milliseconds of a connection in the pool after it is closed.
        idle-timeout: 30000
        connection-timeout: 20000 # INFO: maximum number of milliseconds that a client will wait for a connection
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  cache:
    enabled: false
