logging:
  level:
    root: info
    tech.maze: info
    org.hibernate.SQL: warn
    com.zaxxer.hikari.HikariConfig: warn
    com.zaxxer.hikari: warn
spring:
  main:
    banner-mode: 'off'
  datasource:
    enabled: true
    default:
      configuration:
        maximum-pool-size: 2
        minimum-idle: 2
        max-lifetime: 1800000
        idle-timeout: 30000
        connection-timeout: 20000
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
  cache:
    enabled: false
